<?php
namespace app\admin\controller;
use think\Controller;


class Index extends Login
{

    /**
     * 控制器初始化
     */
    public function _initialize()
    {
        if(session('mitangUser')){
//              var_dump(session('mitangUser')['r_id']);
            $this->userId = session('mitangUser')['id'];
            $this->rId = session('mitangUser')['r_id'];
        }else{
            $this->redirect('login/login');
        }

        if(session('mitangUser')){
            $this->assign('roletype',session('mitangUser')['r_id']);
        }
        // parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return mixed
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbExceptions
     * 首页渲染
     */
    public function index()
    {
        $resultRow = null;
        $start_time = date('Y-m-01', strtotime(date("Y-m-d")));
        $end_time = date('Y-m-d', strtotime("$start_time +1 month -1 day"));
        $userModel = new \app\common\model\User();
        if($this->rId==0){
            $resultRow = $userModel->where(array('is_del'=>0,'id'=>$this->userId))->find();
        }
        if($resultRow){
            $Row = $resultRow->toArray();
            $studentCount = sizeof(explode(',',$Row['s_id']));
            $parentCount = sizeof(explode(',',$Row['f_id']));
        }else{
            $studentCount = $userModel->where(array('r_id'=> 1,'is_del'=>0))->count();
            $parentCount = $userModel->where(array('r_id'=> 2,'is_del'=>0))->count();
            $newAdd = $userModel->where('create_time','between time',[$start_time,$end_time])->where(array('is_del'=>0))->count();
            $this->assign('new_add',$newAdd);
        }
        $this->assign('student_count',$studentCount);
        $this->assign('parent_count',$parentCount);

        return $this->fetch('index');
    }

    /**
     * test
     */
    public function test()
    {
        //var_dump($this->userId);exit;
        $actionLogModel = new \app\common\model\ActionLog();
        $actionLogModel->addActionLog(1,22,'ces',request()->action().request()->controller(),1);
    }
}
