<?php
namespace app\admin\controller;
use think\Controller;

/**
 * Class Inform
 * @package app\admin\controller
 * 通知
 */

class Inform extends Login
{



    const SEX_TYPE = array(
        0  => '未知',
        1  => '男',
        2  => '女',
    );

    public function _initialize()
    {
       if(session('mitangUser')){
          // var_dump(session('mitangUser'));
           $this->userId = session('mitangUser')['id'];
       }else{
           $this->redirect('login/login');
       }
       // parent::_initialize(); // TODO: Change the autogenerated stub
    }

     /**
      * 首页
      */
     public function index()
     {
         $this->assign('page_list',10);
         $this->assign('page',5);
         $this->assign('type',1);
         $this->assign('count',100);
         return $this->fetch('index');
     }

     /**
      * 发布消息
      */
     public function publishTheNews(){
         $this->assign('type',1);
         return $this->fetch('publish_the_news');
     }
}
