<?php
namespace app\admin\controller;
use think\Controller;



class Permission extends Login
{

    /**
     * 权限控制器初始化
     */
    public function _initialize()
    {
        if(session('mitangUser')){
            //   var_dump(session('mitangUser'));
        }else{
            $this->redirect('login/login');
        }
        // parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return mixed四年规划
     */
    public function index()
    {
        return $this->fetch('index');
    }
    /**
     * 添加权限
     */
    public function add()
    {
        return $this->fetch('add');
    }
}
