<?php
namespace app\admin\controller;
use think\Controller;


class Programme extends Login
{

    /**
     * 控制器初始化
     */
    public function _initialize()
    {
        if(session('mitangUser')){
            //   var_dump(session('mitangUser'));
        }else{
            $this->redirect('login/login');
        }
        // parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @return mixed四年规划
     */
    public function index()
    {
        $this->assign('page',10);
        $this->assign('page_list',5);
        return $this->fetch('index');
    }
    /**
     * 测试
     */
    public function test()
    {
        return $this->fetch('test');
    }
}
