<?php
namespace app\admin\controller;
use think\Controller;


class User extends Login
{



    const SEX_TYPE = array(
        0  => '未知',
        1  => '男',
        2  => '女',
    );

    public function _initialize()
    {
       if(session('mitangUser')){
        //   var_dump(session('mitangUser'));
       }else{
           $this->redirect('login/login');
       }
       // parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * return mixed
     * parameter search 查找字段
     * param page 页码
     * param start_time 开始时间
     * param end_time 结束时间
     * param type 类型1家长2学生3老师0管理员
     */
    public function index()
    {
        $userModel = new \app\common\model\User();
        $search = isset($_POST['search']) ? $_POST['search'] : null;
        $page = isset($_POST['page']) ? $_POST['page'] : 1;
        $start_time = !empty($_POST['start_time']) ? $_POST['start_time'] : '2018-01-01 00:00:00';
        $end_time = !empty($_POST['end_time']) ? $_POST['end_time'] : '2028-01-01 00:00:00';
        $page = isset($_GET['page']) ? $_GET['page'] : 0;
       // $type = isset($_POST['type']) ? $_POST['type'] : 2;
        $type = isset($_GET['type']) ? $_GET['type'] : 2;
        $limit =10;
        $offset = $page * $limit;
        if(empty($search)){
            $userRows = $userModel->where(array('is_show'=>1,'is_del'=>0,'r_id'=>$type))->where('create_time','between time',[$start_time,$end_time])->field($userModel->field)->limit($offset,$limit)->select()->toArray();
            $count  = $userModel->where(array('is_show'=>1,'is_del'=>0,'r_id'=>$type))->where('create_time','between time',[$start_time,$end_time])->field($userModel->field)->limit($offset,$limit)->count();
        }else{
            $userRows = $userModel->where(array('is_show'=>1,'is_del'=>0,'r_id'=>$type))->where($userModel->fuzzy_query,'like','%'.$search.'%')->where('create_time','between time',[$start_time,$end_time])->field($userModel->field)->limit($offset,$limit)->select()->toArray();
            $count = $userModel->where(array('is_show'=>1,'is_del'=>0,'r_id'=>$type))->where($userModel->fuzzy_query,'like','%'.$search.'%')->where('create_time','between time',[$start_time,$end_time])->field($userModel->field)->limit($offset,$limit)->count();
        }
        $pageList =ceil($count / $limit);
        $this->assign('list',$userRows);
        $this->assign('r_id',$type);
        $this->assign('page',$page);
        $this->assign('count',$count);
        $this->assign('page_list',$pageList);
        return $this->fetch('index');
    }



    /**
     *  新增用户
     */
    public function add()
    {
        return $this->fetch('add');
    }



    /**
     * 修改用户
     * param id 用户自增编号
     */
    public function edit()
    {
        $returnArray = array();
        $actionLogModel = new \app\common\model\ActionLog();
        if(!empty($_POST['id'])){
            $userModel =new \app\common\model\User();
            $userRow = $userModel->get($_POST['id']);
        }else{

        }
    }



    /**
     * 添加用户
     * userAction
     */

    public function addAction()
    {
        $returnArray = array();
        $street_address = '';
      //  var_dump(session('mitangUser'));
        $actionModel = new \app\common\model\ActionLog();


        if (!empty($_POST['FirstName'])) {
            $xing = $_POST['FirstName'];
        } else {
            $returnArray = array(
                'code' => 100006,
                'mssg' => $actionModel::ERRORCODE[100006],
                'data' => array()
            );
        }

        if (!empty($_POST['LastName'])) {
            $ming = $_POST['LastName'];
        } else {
            $returnArray = array(
                'code' => 100007,
                'mssg' => $actionModel::ERRORCODE[100007],
                'data' => array()
            );
        }

        $data['sex'] = isset($_POST['sex']) ? $_POST['sex'] : 0;
        $data['nationality'] = isset($_POST['nationality']) ? $_POST['nationality'] : '中国';


        if (!empty($_POST['telephone'])) {
            $data['telephone'] = $_POST['telephone'];
            echo substr($data['telephone'] ,-2,6);exit;
            $data['password'] = sha1($data['telephone']);
        }else{
            $returnArray = array(
                'code' => 100008,
                'mssg' => $actionModel::ERRORCODE[100008],
                'data' => array()
            );
        }

        if(!empty($_POST['birth_date'])){
             $data['birth_date'] = $_POST['birth_date'];
        }

        if(!empty($_POST['passport_no'])){
            $data['passport_no'] = $_POST['passport_no'];
        }
        if(!empty($_POST['passport_issue_date'])){
            $data['passport_issue_date'] = $_POST['passport_issue_date'];
        }
        if(!empty($_POST['passport_expiry_date'])){
            $data['passport_expiry_date'] = $_POST['passport_expiry_date'];
        }
        if(!empty($_POST['emergency_contact'])){
            $data['emergency_contact'] = $_POST['emergency_contact'];
        }
        if(!empty($_POST['emergency_telephone'])){
            $data['emergency_telephone'] = $_POST['emergency_telephone'];
        }

        if(!empty($_POST['parent_name'])){
            $parentName = $_POST['parent_name'];
        }
        if(!empty($_POST['parent_last_name'])){
            $parentLastName = $_POST['parent_last_name'];
        }
        if(!empty($_POST['parent_telephone'])){
            $data['parent_telephone'] = $_POST['parent_telephone'];
        }
        if(!empty($_POST['parent_birth_date'])){
            $data['parent_birth_date'] = $_POST['parent_birth_date'];
        }
        if(!empty($_POST['parent_company'])){
            $data['parent_company'] = $_POST['parent_company'];
        }
        if(!empty($_POST['parent_job'])) {
            $data['parent_job'] = $_POST['parent_job'];
        }
        if (!empty($_POST['parent_nationality'])) {
            $data['parent_nationality'] = $_POST['parent_nationality'];
        }



        if (!empty($_POST['street_address'])) {
            $street_address = $_POST['street_address'];
        }

        if (!empty($_POST['permanent_zip_code'])) {
            $data['email'] = $_POST['permanent_zip_code'];
        }



        if (!empty($_POST['permanent_province']) && !empty($_POST['permanent_city']) && !empty($_POST['permanent_district']) ) {
            $data['email_address'] = $_POST['permanent_province'].'|'.$_POST['permanent_city'].'|'.$_POST['permanent_district'].'|'.$street_address;
        }

        if (!empty($_POST['permanent_telephone'])) {
            $data['permanent_telephone'] = $_POST['permanent_telephone'];
        }

        if (!empty($_POST['permanent_date'])) {
            $data['permanent_date'] = $_POST['permanent_date'];
        }
        if (!empty($_POST['mailing_street_address'])) {
            $data['parent_nationality'] = $_POST['mailing_street_address'];
        }






    }
    /**
     * 删除用户
     * parm id
     */
    public function delAction()
    {
        $actionLogModel = new \app\common\model\ActionLog();
        $userModel = new \app\common\model\User();
        $returnArray = array();
        if(!empty($_POST['id'])){
            $userModel = new \app\common\model\User();
            $userRow = $userModel->where('id',$_POST['id'])->update(array('is_del'=>1,'update_time'=>date('Y-m-d H:i:s')));
            if($userRow){
                $returnArray = array(
                    'code' => 1,
                    'mssg' => $actionLogModel::ERRORCODE[1],
                    'data' => array()
                );
              //  $actionLogModel->addActionLog(1,$this->user_id,$this->username,'删除了编号为'.$_POST['id'].'的用户');
            }else{
                $returnArray = array(
                    'code' => 100002,
                    'mssg' => $actionLogModel::ERRORCODE[100002],
                    'data' => array()
                );
            }
        }else{
           $returnArray = array(
                'code' => 100001,
                'mssg' => $actionLogModel::ERRORCODE[100001],
                'data' => array()
           );
        }
        return $returnArray;
    }
}
